# -*- coding: utf-8 -*-
"""AlunoMedia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Grm7P4Eoam2vW8ROA_ICjwUlocsAw7Q
"""

aluno = input ('digite o nome do aluno:')
n1 = float (input ('digite a primeira nota:'))
n2 = float (input('digite a segunda nota:'))
n3 = float (input('digite a terceira nota:'))

media = (n1+n2+n3)/3

if media >= 7:
   situaçao = 'aprovado'
elif media >= 4:
   situaçao = 'em recuperação'
else:
   situaçao = 'reprovado'
print(f'o Aluno {aluno} esta em situaçao {situaçao} com media {media}')